### ISSUE TITLE
Unimplemented notification type "encrypt" crash

### ISSUE THREAD

**Issue by frankmuc** [tgalal/yowsup#1017]
This happens every couple of times and a full reinstall via git does not fix this issue. Sometimes it is fixed on it's own, right now it is crashing again.

root@debian:/yowsup# yowsup-cli demos --yowsup -c config.yowsup >>log /L Traceback (most recent call last):   File "/usr/local/bin/yowsup-cli", line 4, in <module>     __import__('pkg_resources').run_script('yowsup2==2.3.185', 'yowsup-cli')   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 534, in run_script     self.require(requires)[0].run_script(script_name, ns)   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1445, in run_script     exec(script_code, namespace, namespace)   File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 327, in <module>        File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 231, in process        File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.185-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 259, in startCmdline        File "build/bdist.linux-x86_64/egg/yowsup/demos/cli/stack.py", line 25, in start   File "build/bdist.linux-x86_64/egg/yowsup/stacks
/yowstack.py", line 167, in loop   File "/usr/lib/python2.7/asyncore.py", line 216, in loop     poll_fun(timeout, map)   File "/usr/lib/python2.7/asyncore.py", line 156, in poll     read(obj)   File "/usr/lib/python2.7/asyncore.py", line 87, in read     obj.handle_error()   File "/usr/lib/python2.7/asyncore.py", line 83, in read     obj.handle_read_event()   File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event     self.handle_read()   File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 73, in handle_read   File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 80, in receive   File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 55, in toUpper   File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive   File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived   File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 55, in toUpper   File "build/bdist.linux-x86_64/egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive   File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 55, in toUpper   File "build/bdist.linux-x86_64/egg/yowsup/layers/coder/layer.py", line 35, in receive   File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 55, in toUpper   File "build/bdist.linux-x86_64/egg/yowsup/layers/logger/layer.py", line 14, in receive   File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 55, in toUpper   File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 160, in receive   File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 101, in receive   File "build/bdist.linux-x86_64/egg/yowsup/layers/protocol_notifications/layer.py", line 41, in recvNotification   File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 117, in raiseErrorForNode ValueError: Unimplemented notification type <notification type="encrypt" offline="3" from="s.whatsapp.net" id="2707474780" t="1440497635"> <count value="0"> </count> </notification>

**Comment by frankmuc** [comment]
"build/bdist.linux-x86_64/egg/yowsup/layers/protocol_notifications/layer.py", line 41, in recvNotification   File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 117, in raiseErrorForNode ValueError: Unimplemented notification type <notification type="encrypt" offline="3" from="s.whatsapp.net" id="2707474780" t="1440497635"> <count value="0"> </count> </notification>

**Comment by Dl0tt** [comment]
add YowAxolotlLayer to you stack on run.py or a -moxie argument to the command line with yowsup-cli

-------- Original Message --------

**Comment by frankmuc** [comment]
There is no -moxie option any longer and has no effect anyway:

WARNING:yowsup-cli:--moxie/-m is deprecated and will be removed soon as e2e encryption is now almost mandatory.

And I don't use or have a run.py. What are you referring to?

This issue should be fixed in the main code rather than discussing quick hacks.

**Comment by tgalal** [comment]
@frankmuc --moxie option still exist and is not a quick hack
