### ISSUE TITLE
Number Registration Status : fail, reason :Old Version

### ISSUE THREAD

**Issue by samme13** [tgalal/yowsup#2113]
Hi,
I keep getting this.

status: fail
reason: old_version
login: 25XXXXXXXXXX8

Could someone please help me or point me to the right direction.
Kindly

**Comment by faapa** [comment]
hi, you have a solution ?.
 i have identical problem

**Comment by rhuantac** [comment]
Hey, check this solution #2090 .

**Comment by faapa** [comment]
The problem was solved, thanks

**Comment by kingalione** [comment]
Solution #2090 did not worked for me. However what is working for me is to go to the yowsup directory and call the cli like this: ./yowsup-cli

**Comment by superhero1** [comment]
#1905 works.

**Comment by Aswinth-raj** [comment]
No it does not work as on 4-10-2017.

I have followed the changes suggested in 
https://github.com/tgalal/yowsup/issues/1905
https://github.com/tgalal/yowsup/issues/2090

Still no luck. I have the old_version error. Any help pls?

**Comment by Birgobert** [comment]
i know it's an old thread, but if someone still has problems with the registration. 

Here, the way to get the current version and _MD5_CLASS of WhatsApp is described. 

[https://iamjagjeetubhi.wordpress.com/2017/09/21/how-to-use-yowsup-the-python-whatsapp-library-in-ubuntu/#step2](url)

**Comment by NocivoCracker** [comment]
**ado a ado quem leu é viado**
