### ISSUE TITLE
Stopped connecting on whatsapp today:  General: Login Failed, reason: 405

### ISSUE THREAD

**Issue by rafaelnordavind** [tgalal/yowsup#3074]
Stopped connecting on whatsapp today

`[offline]:/L                                                                                                I 2021-05-20 14:29:39,417 yowsup.layers.network.layer - Connecting to e4.whatsapp.net:443                   I 2021-05-20 14:29:39,601 yowsup.axolotl.manager - Generating 812 prekeys, current max_prekey_id=0          I 2021-05-20 14:29:40,040 yowsup.axolotl.manager - Storing 812 prekeys                                      I 2021-05-20 14:29:44,886 yowsup.axolotl.manager - Loaded 812 unsent prekeys                                general: Login Failed, reason: 405                                                                          general: Disconnected: Authentication Failure                                                               [offline]:                `

**Comment by rafaelnordavind** [comment]
Fixed after upgrade version and ClassesDex on env_android.py file

`#Version: 2.21.10.13  #used only in registration                                                                                                                                                                       
Version: 2.21.10                                                                                                                                                                           ClassesDex: +swPH4BPcTUjyXCFPAW/LQ==    `

**Comment by Asatecore** [comment]
rafael can you send demo message?

**Comment by rafaelnordavind** [comment]
> rafael can you send demo message?

`[offline]:/L
D 2021-05-20 17:27:11,367 yowsup.layers.network.layer - Created asyncore dispatcher
I 2021-05-20 17:27:11,368 yowsup.layers.network.layer - Connecting to e5.whatsapp.net:443
D 2021-05-20 17:27:11,368 yowsup.layers.network.dispatcher.dispatcher_asyncore - connect(('e5.whatsapp.net', 443))
D 2021-05-20 17:27:11,537 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_connect
D 2021-05-20 17:27:11,537 yowsup.layers.network.layer - Connected
D 2021-05-20 17:27:11,538 yowsup.axolotl.factory - get_manager(profile_name=[anonimized], username=[anonimized])
D 2021-05-20 17:27:11,547 yowsup.axolotl.manager - Initialized AxolotlManager [username=[anonimized], db=/home/[anonimized]/.config/yowsup/[anonimized]/axolotl.db]
D 2021-05-20 17:27:11,548 yowsup.axolotl.manager - level_prekeys(force=False)
D 2021-05-20 17:27:11,555 yowsup.axolotl.manager - len(pending_prekeys) = 812
D 2021-05-20 17:27:11,556 yowsup.axolotl.manager - load_unsent_prekeys
D 2021-05-20 17:27:11,556 yowsup.layers.noise.layer - Received auth event
D 2021-05-20 17:27:11,559 yowsup.env.env - Env not set, setting it to android
D 2021-05-20 17:27:11,559 yowsup.env.env - Current env changed to android
D 2021-05-20 17:27:11,560 yowsup.layers.noise.layer - Performing handshake [username= [anonimized], passive=False]
D 2021-05-20 17:27:11,564 yowsup.layers.noise.layer - Starting handshake worker
D 2021-05-20 17:27:11,770 yowsup.profile.profile - write_config for [anonimized]
D 2021-05-20 17:27:11,771 yowsup.common.tools - writeProfileData(profile_name=[anonimized], name=config.json, val=[omitted])
D 2021-05-20 17:27:11,772 yowsup.common.tools - Writing /home/[anonimized]/.config/yowsup/[anonimized]/config.json
D 2021-05-20 17:27:11,975 yowsup.layers.logger.layer - rx:
<failure reason="405" location="frc" />
general: Login Failed, reason: 405
D 2021-05-20 17:27:11,976 yowsup.layers.network.dispatcher.dispatcher_asyncore - disconnect
D 2021-05-20 17:27:11,976 yowsup.layers.network.dispatcher.dispatcher_asyncore - handle_close
D 2021-05-20 17:27:11,976 yowsup.layers.network.layer - Disconnected
D 2021-05-20 17:27:12,030 yowsup.layers.axolotl.layer_control - Disconnected, reboot_connect? = False
general: Disconnected: Authentication Failure`

**Comment by Asatecore** [comment]
you need to modify more files, but even though I have already modified those files I still have problems sending messages.

check this out so you can make some progress #3045
