### ISSUE TITLE
Echo Client crash new number

### ISSUE THREAD

**Issue by Parnassian** [tgalal/yowsup#939]
Just like #937 yowsup crashes when a user sends me a message that has never send me a message.

I do not have a crash log since I did not enable debugging.

I used the latest echo client example in the repo.

When I was using the yowsup cli command line tool, the tool also crashed whilst sending a message to someone I never have send a message to. I synced my contactlist with the phonenumber I sent the message too and after that it worked.

Maybe in the echo client it needs to sync the new contact when it sends a message and than respond to it? If somebody is already doing that please show me how you do it.

Looking forward to a reply.

**Comment by rami-dabain** [comment]
no the problem that it is looking in a key-valie storage to find a number
by name and it does not find it.

**Comment by Parnassian** [comment]
Thank you for your reply. When I reboot the echo client it sends the messages just fine. Do you know how to fix it or do you just restart your application?

**Comment by rami-dabain** [comment]
I fixed it but currently I am traveling and can't edit any code

**Comment by Parnassian** [comment]
I see, can you point me where I can fix it myself or is it much code? If so, when will you be back?

Have fun on your journey :)

**Comment by abhiramnarla** [comment]
@Parnassian  Did you resolve the issue?

**Comment by abhiramnarla** [comment]
@Parnassian  I have updated yowsup to it latest release and the problem is still not resolved. 
I'm still getting this error when some one text messages me for the first time.
Exception: No such signedprekeyrecord! 24006 
But if I send a media message from that no i.e share my location then the problem is resolved. Any suggestions would be great. Thank you.

**Comment by Votyer** [comment]
I found the same issue with last version.

**Comment by tgalal** [comment]
Please try code from develop branch

**Comment by Votyer** [comment]
I tried with develop branch but I got a new error. 
Please find the stack trace below
    
  File "build/bdist.linux-x86_64/egg/yowsup/demos/echoclient/stack.py", line 49, in start
  File "build/bdist.linux-x86_64/egg/yowsup/stacks/yowstack.py", line 175, in loop
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 73, in handle_read
  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 80, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 55, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 55, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 55, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/coder/layer.py", line 35, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 55, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/logger/layer.py", line 14, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 55, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 160, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 101, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/protocol_messages/layer.py", line 20, in recvMessageStanza
  File "build/bdist.linux-x86_64/egg/yowsup/layers/protocol_messages/protocolentities/message_text.py", line 38, in fromProtocolTreeNode
AttributeError: 'NoneType' object has no attribute 'getData'

**Comment by tgalal** [comment]
I'm guessing your are getting v2 encrypted messages which is still work in progress, try with --debug and post the node please.

**Comment by CharlesOkwuagwu** [comment]
@tgalal 
...but we have covered v=2, what's left ?

**Comment by tgalal** [comment]
@CharlesOkwuagwu  can you help with 7 bit length part?

**Comment by CharlesOkwuagwu** [comment]
@tgalal sure see my solution here:
http://stackoverflow.com/questions/31501672/unusual-integer-encoding-to-bytes-what-scheme-is-this/31503832#31503832 

It's VB.Net but you get the picture

**Comment by CharlesOkwuagwu** [comment]
You only care about the length conversion when you are sending a message - it's irrelevant when receiving.

**Comment by CharlesOkwuagwu** [comment]
(my python sucks so... VB.net :) )

    Function DecodeV2(data As Byte()) As Byte()
        Select Case data.Length
            Case Is < 3 + 128
                Return Slice(data, 2, data.Length - 3)
            Case Is < 3 + (128 * 128)
                Return Slice(data, 3, data.Length - 4)
            Case Else 'messages longer than 16,384 !?!
                Return data
        End Select
    End Function

    Function EncodeV2(data As Byte()) As Byte()
        Dim len = data.Length
        Dim a = New List(Of Byte)
        a.Add(&HA)

        If len < 128 Then
            a.Add(CByte(len))
        Else
            Dim v = CShort(len)
            a.Add(CByte((v And &HFF) Or &H80))
            v >>= 7
            a.Add(CByte((v And &HFF)))
        End If

        a.AddRange(data)
        a.Add(&H1)

        Return a.ToArray
    End Function

**Comment by CharlesOkwuagwu** [comment]
I am assuming messages will *ALWAYS* be < 128*128 (i.e 16,384) characters long
Hence the simplifications above.

**Comment by tgalal** [comment]
@CharlesOkwuagwu got it to work, thanks!

**Comment by CharlesOkwuagwu** [comment]
@tgalal cool!

**Comment by tgalal** [comment]
@CharlesOkwuagwu but how to determine where decrypted message content offset (to discard LEN) ?

**Comment by CharlesOkwuagwu** [comment]
@tgalal the format is simple: 

for message len < 128 length will always be encoded with one byte, so message starts from third byte, hence Slice(data, 2, data.Length - 3)

**Comment by CharlesOkwuagwu** [comment]
@tgalal 

for message len >=128, < 128*128 length will always be encoded with two bytes, so message starts from fourth byte, hence Slice(data, 3, data.Length - 3)

**Comment by Votyer** [comment]
I tested with develop branch and now single message and group messagges wroks.
But i found some problems with MP4, in fact when yowsup receive the video returns the following error
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 5, in <module>
    pkg_resources.run_script('yowsup2==2.3.183', 'yowsup-cli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1401, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 327, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 233, in process
    
  File "/usr/local/lib/python2.7/dist-packages/yowsup2-2.3.183-py2.7.egg/EGG-INFO/scripts/yowsup-cli", line 269, in startEcho
    
  File "build/bdist.linux-x86_64/egg/yowsup/demos/echoclient/stack.py", line 49, in start
  File "build/bdist.linux-x86_64/egg/yowsup/stacks/yowstack.py", line 175, in loop
  File "/usr/lib/python2.7/asyncore.py", line 216, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python2.7/asyncore.py", line 156, in poll
    read(obj)
  File "/usr/lib/python2.7/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 73, in handle_read
  File "build/bdist.linux-x86_64/egg/yowsup/layers/network/layer.py", line 80, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 55, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 28, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/stanzaregulator/layer.py", line 48, in processReceived
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 55, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/auth/layer_crypt.py", line 63, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 55, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/coder/layer.py", line 35, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 55, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/logger/layer.py", line 14, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 55, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 103, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 127, in onMessage
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 55, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 160, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 101, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/layers/protocol_media/layer.py", line 48, in recvMessageStanza
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 55, in toUpper
  File "build/bdist.linux-x86_64/egg/yowsup/layers/interface/interface.py", line 71, in receive
  File "build/bdist.linux-x86_64/egg/yowsup/demos/echoclient/layer.py", line 13, in onMessage
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toLower
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 164, in send
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 107, in send
  File "build/bdist.linux-x86_64/egg/yowsup/layers/protocol_media/layer.py", line 35, in sendMessageEntity
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 111, in entityToLower
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toLower
  File "build/bdist.linux-x86_64/egg/yowsup/layers/axolotl/layer.py", line 95, in send
  File "build/bdist.linux-x86_64/egg/yowsup/layers/__init__.py", line 59, in toLower
  File "build/bdist.linux-x86_64/egg/yowsup/layers/logger/layer.py", line 8, in send
  File "build/bdist.linux-x86_64/egg/yowsup/structs/protocoltreenode.py", line 81, in __str__
  File "build/bdist.linux-x86_64/egg/yowsup/structs/protocoltreenode.py", line 73, in toString
  File "build/bdist.linux-x86_64/egg/yowsup/structs/protocoltreenode.py", line 53, in toString
TypeError: cannot concatenate 'str' and 'NoneType' objects
